USE PD326

SELECT * FROM User;
SELECT * FROM Student;


CREATE TABLE Student(
	SId INT PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100),
	Address VARCHAR(MAX),
	Contact VARCHAR(50),
	Email VARCHAR(50),
	Gender VARCHAR(10),
	CountryId INT FOREIGN KEY REFERENCES SCountry(CountryId),
	StateId INT FOREIGN KEY REFERENCES SState(StateId),
	CityId INT FOREIGN KEY REFERENCES SCity(CityId),
	Password VARCHAR(50)
);

ALTER TABLE Student
DROP COLUMN Password;

CREATE TABLE SCountry(
	CountryId INT PRIMARY KEY IDENTITY(1,1),
	CountryName VARCHAR(200)
);

CREATE TABLE SState(
	StateId INT PRIMARY KEY IDENTITY(1,1),
	StateName VARCHAR(200),
	CountryId INT FOREIGN KEY REFERENCES SCountry(CountryId)
);

CREATE TABLE SCity(
	CityId INT PRIMARY KEY IDENTITY(1,1),
	CityName VARCHAR(200),
	StateId INT FOREIGN KEY REFERENCES SState(StateId),
	CountryId INT FOREIGN KEY REFERENCES SCountry(CountryId)
);